[workspace]

members = [
  "branches",
  "guessing_game",
  "functions_learn",
  "ownership_learn",
  "match_learn",
  "reference_borrowing",
  "slice_learn",
  "variables_learn",
  "struct_learn",
  "algo_learn",
  "enums_learn",
  "match_learn",
  "iflet_learn", "example", "Function_and_ControlFlow",
]

resolver = "3"
