[workspace]

members = [
  "branches",
  "guessing_game",
  "functions_learn",
  "ownership_learn",
  "match_learn",
  "reference_borrowing",
  "slice_learn",
  "variables_learn",
  "struct_learn",
  "algo_learn",
  "enums_learn",
  "if_let_learn",
  "example",
  "function_and_control_flow",
  "temp_converter",
  "nth_fibonacci",
  "ownership_examples",
  "borrow_and_reference",
  "collections_learn",
  "hash_map", "panic_learn",
]

resolver = "3"
